sudo: false

language: java

jdk:
  - oraclejdk8
  - oraclejdk7

os:
  - linux

install:
  - mvn dependency:go-offline -B -V

script:
  - mvn clean verify -Dgpg.skip=true -B -V

cache:
  directories:
  - $HOME/.m2
